/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)', 'Pretendard', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        display: ['var(--font-display)', 'MaruBuri', 'Iowan Old Style', 'Georgia', 'serif'],
      },
      maxWidth: {
        'container-xl': 'var(--container-xl)',
        'container-lg': 'var(--container-lg)',
        'container-md': 'var(--container-md)',
        'container-sm': 'var(--container-sm)',
        'prose-narrow': '28rem',
        'prose': '35rem',
        'ch-7': '7.2em',
        'ch-9': '9.5ch',
      },
      fontSize: {
        '2xs': 'var(--text-2xs)',
        'md': 'var(--text-md)',
        '5xl': 'var(--text-5xl)',
        '6xl': 'var(--text-6xl)',
        '7xl': 'var(--text-7xl)',
        '8xl': 'var(--text-8xl)',
        '9xl': 'var(--text-9xl)',
      },
      colors: {
        // LIDER Oatmeal + Catalyst Design System
        canvas: {
          DEFAULT: 'var(--canvas)',
          muted: 'var(--canvas-muted)',
          soft: 'var(--canvas-soft)',
        },
        surface: {
          DEFAULT: 'var(--surface)',
          strong: 'var(--surface-strong)',
          soft: 'var(--surface-soft)',
          tint: 'var(--surface-tint)',
          overlay: 'var(--surface-overlay)',
          // Alpha variants
          70: 'var(--surface-70)',
          80: 'var(--surface-80)',
          82: 'var(--surface-82)',
          84: 'var(--surface-84)',
          86: 'var(--surface-86)',
          88: 'var(--surface-88)',
          90: 'var(--surface-90)',
          92: 'var(--surface-92)',
          94: 'var(--surface-94)',
          96: 'var(--surface-96)',
          98: 'var(--surface-98)',
          // Action surface alphas
          'action-72': 'var(--action-surface-72)',
          'action-76': 'var(--action-surface-76)',
          'action-78': 'var(--action-surface-78)',
          'action-82': 'var(--action-surface-82)',
          // Brand surface alphas
          'brand-10': 'var(--brand-surface-10)',
          'brand-12': 'var(--brand-surface-12)',
          'brand-14': 'var(--brand-surface-14)',
          // Warning surface alphas
          'warning-10': 'var(--warning-surface-10)',
          // Dark surface alphas
          'dark-10': 'var(--dark-surface-10)',
          'dark-12': 'var(--dark-surface-12)',
          'dark-82': 'var(--dark-surface-82)',
          'dark-92': 'var(--dark-surface-92)',
        },
        brand: {
          900: 'var(--brand-900)',
          800: 'var(--brand-800)',
          700: 'var(--brand-700)',
          600: 'var(--brand-600)',
          500: 'var(--brand-500)',
        },
        action: {
          700: 'var(--action-700)',
          600: 'var(--action-600)',
          500: 'var(--action-500)',
          100: 'var(--action-100)',
        },
        text: {
          strong: 'var(--text-strong)',
          primary: 'var(--text-primary)',
          muted: 'var(--text-muted)',
          soft: 'var(--text-soft)',
        },
        border: {
          subtle: 'var(--border-subtle)',
          strong: 'var(--border-strong)',
          accent: 'var(--border-accent)',
          overlay: 'var(--border-overlay)',
          // Brand border alpha variants
          'brand-10': 'var(--brand-border-10)',
          'brand-12': 'var(--brand-border-12)',
          'brand-14': 'var(--brand-border-14)',
          'brand-16': 'var(--brand-border-16)',
        },
        success: {
          600: 'var(--success-600)',
          100: 'var(--success-100)',
        },
        warning: {
          600: 'var(--warning-600)',
          100: 'var(--warning-100)',
        },
        danger: {
          600: 'var(--danger-600)',
          100: 'var(--danger-100)',
        },
        info: {
          600: 'var(--info-600)',
          100: 'var(--info-100)',
        },
        emotion: {
          accent: 'var(--emotion-accent)',
          surface: 'var(--emotion-surface)',
          border: 'var(--emotion-border)',
        },
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        'full': 'var(--radius-full)',
      },
      spacing: {
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '10': 'var(--space-10)',
        '14': 'var(--space-14)',
      },
      boxShadow: {
        'card': 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        'float': 'var(--shadow-float)',
        'glass': '0 8px 32px rgba(0, 0, 0, 0.08)',
        'glass-lg': '0 16px 48px rgba(0, 0, 0, 0.12)',
        'soft': '0 4px 20px rgba(0, 0, 0, 0.05)',
        'focus': '0 0 0 3px var(--focus-ring)',
        'focus-strong': '0 0 0 3px var(--focus-ring-strong)',
      },
      transitionTimingFunction: {
        'smooth': 'var(--ease-smooth)',
        'soft': 'var(--ease-soft)',
      },
      transitionDuration: {
        'fast': 'var(--duration-fast)',
        'normal': 'var(--duration-normal)',
        'slow': 'var(--duration-slow)',
      },
      letterSpacing: {
        'kicker': 'var(--tracking-kicker)',
        'label': 'var(--tracking-label)',
        'step': 'var(--tracking-step)',
        'card': 'var(--tracking-card)',
        'badge': 'var(--tracking-badge)',
        'mobile': 'var(--tracking-mobile)',
        'tiny': 'var(--tracking-tiny)',
        'min': 'var(--tracking-min)',
        'tight-hero': '-0.055em',
        'tight-section': '-0.045em',
        'tight-heading': '-0.035em',
        'brand': '0.08em',
      },
      lineHeight: {
        'hero': 'var(--leading-hero)',
        'section': 'var(--leading-section)',
        'heading': 'var(--leading-heading)',
      },
      backdropBlur: {
        xs: '2px',
      },
      gridTemplateColumns: {
        'hero': 'var(--grid-hero)',
        'hero-sidebar': 'var(--grid-hero-sidebar)',
        'problem': 'var(--grid-problem)',
        'why-now': 'var(--grid-why-now)',
        'report': 'var(--grid-report)',
        'steps': 'var(--grid-steps)',
        'form-submit': '1fr auto',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-in': 'slideIn 0.3s ease-out',
        'bounce-slow': 'bounce 3s infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(19, 125, 128, 0.4)' },
          '100%': { boxShadow: '0 0 20px rgba(19, 125, 128, 0.6)' },
        },
      },
    },
  },
  plugins: [],
}
